<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Outwardly</title>
</head>
<body>
  <header>
    <h1>Outwardly</h1>
    <p>Where communities thrive</p>
  </header>
  <main>
    <section id="about">
      <h2>About</h2>
      <p>Outwardly is a community for people who want to connect with others who share their interests.</p>
      <p>Create a community, join a community, or simply learn more about what's happening in your community.</p>
    </section>
    <section id="logo">
      <img src="images/logo.png" alt="Outwardly logo">
    </section>
    <section id="discussion">
      <h2>Discussion</h2>
      <p>Discuss anything and everything related to Outwardly.</p>
      <ul>
        <li><a href="#">New community created</a></li>
        <li><a href="#">Discussion about the latest news</a></li>
        <li><a href="#">Ask a question</a></li>
      </ul>
    </section>
    <section id="updates">
      <h2>Updates</h2>
      <p>Stay up-to-date on the latest news and events from Outwardly.</p>
      <ul>
        <li>New features coming soon</li>
        <li>Community events happening this week</li>
        <li>Opportunities to get involved</li>
      </ul>
    </section>
  </main>
  <footer>
    <p>Copyright &copy; 2024 Outwardly</p>
  </footer>
</body>
</html>
